apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-creator-binding
subjects:
- kind: ServiceAccount
  name: default  # Replace with your service account name if it's different
  namespace: dena
roleRef:
  kind: ClusterRole
  name: job-creator-role  
  apiGroup: rbac.authorization.k8s.io
