apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data-pvc
  namespace: dena
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cassandra
  resources:
    requests:
      storage: 1Gi
