apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-service
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
      - name: ui-service-container
        image: gsiatras13/map-reduce-ui-linux:latest
        ports:
        - containerPort: 8080
