apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-pv-1
  namespace: dena
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: cassandra  # Ensure this matches your StorageClass
  persistentVolumeReclaimPolicy: Delete  # Adjust as per your retention policy
  claimRef:
    namespace: dena
    name: cassandra-data  # Replace with your PVC name
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2 
