apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-pv-1
  namespace: dena
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: cassandra
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data/cassandra  # Adjust this path as needed on your host machine

