apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio
  namespace: dena
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio
  hostPath:
    path: /mnt/data/minio  # Replace with an actual path on your host
