apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: dena
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio
  resources:
    requests:
      storage: 1Gi  # Requesting 1GiB of storage
