apiVersion: v1
kind: Service
metadata:
  name: cassandra-nodeport
  namespace: dena
spec:
  type: NodePort
  ports:
    - port: 9042   # Port on which the service will be accessible
      targetPort: 9042  # Port on the pods that the service will forward to
      nodePort: 32000  # Choose a high port number, in this case, 32000
  selector:
    app: cassandra    # Match labels of your Cassandra pods
