apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  type: LoadBalancer
  selector:
    app: ui-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
